name: Deploy to GitHub Pages
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pages-deploy
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'chore(main): release')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure custom domain
        run: echo 'maponphoto.eu' > dist/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: "github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'chore(main): release')"
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4