name: Deploy to GitHub Pages

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  verify-deploy-comment:
      name: Verify requirements to deploy to GitHub Pages
      runs-on: ubuntu-latest
      outputs:
        DEPLOY_GHP: ${{ steps.check.outputs.triggered == 'true' }}
      steps:
        - uses: khan/pull-request-comment-trigger@v1.1.0
          id: check
          with:
            trigger: "[x] Deploy to GitHub Pages"
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: verify-deploy-comment
    if: inputs.DEPLOY_GHP
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./dist

#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./dist

