name: Code Review by ChatGPT

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  verify-chat-gpt-review:
    name: Verify requirements to ask ChatGPT of code review
    runs-on: ubuntu-latest
    outputs:
      RUN_CHAT_GPT: ${{ steps.check.outputs.triggered == 'true' }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: "[x] ChatGPT Review"

  gpt-code-review:
    name: ChatGPT Code Review
    runs-on: ubuntu-latest
    needs: verify-chat-gpt-review
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        name: ChatGPT-CodeReview
        with:
          RUN_CHAT_GPT: ${{ needs.verify-chat-gpt-review.outputs.RUN_CHAT_GPT == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.GITHUBPR_MAP_ON_PHOTO }}

