name: Release Please

# Workflow odpowiedzialny za automatyczne generowanie PR z dev do main z nowymi wersjami

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: 📦 Przygotowanie release PR
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Uruchom Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: map-on-photo
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
