name: Release Please

# Workflow odpowiedzialny za automatyczne generowanie PR do brancha release z nowymi wersjami

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    name: 📦 Przygotowanie release PR
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Uruchom Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          config-file: .release-please-config.json

  